version: '3.9'

services:
  user:
    image: microservices/user
  database:
    image: microservices/database
  web:
    image: microservices/web
    environment:
      Authentication__GitHub__ClientId: '${GitHub__ClientId}'
      Authentication__GitHub__ClientSecret: '${GitHub__ClientSecret}'
      ConnectionStrings__DatabaseService: 'http://database:80'
      ConnectionStrings__UserService: 'http://user:80'
  proxy:
    image: caddy:2
    ports:
      # - 80:80
      # - 443:443
      - 8443:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
