version: '3.9'

services:
  authentication:
    image: microservices/authentication
    environment:
      AppSettings__ConnectionStrings__DatabaseService: 'http://database'
  database:
    image: microservices/database
    environment:
      ConnectionStrings__DatabaseService: 'abc'
  web:
    image: microservices/web
    environment:
      AppSettings__ConnectionStrings__AuthenticationService: 'http://authentication'
      AppSettings__ConnectionStrings__DatabaseService: 'http://database'
    ports:
      - 8080:80
